= LED Strip Controller

An LED strip controller for up to three RGB[W] LED strips, controlled over WiFi + MQTT.


== Current State

* Hardware
** Circuit schematic: nearly complete (for an initial version); some lines required for firmware programming are still missing.
** PCB layout: not yet started.
* Software: prototype exists; will be released in the following weeks after some cleanup and polishing. 


== Features

Up to three independently controllable LED strips: ::
+
--
When decorating shelves, TV racks or similar with LED strips, having several
shorter strips glowing in different colors can look nicer than having one longer strip.
However, with usual LED strip controllers, each strip requires its own controller plus power supply. In the end, all those small boxes and their
power bricks don't really look all that pretty.

With this controller, three separate LED strips can be driven with just one small box and its power brick.
--

MQTT interface: ::
+
--
The controller connects (via WiFi) to an MQTT broker, from which it receives
commands and to where it posts its current state.

Right now, the controller supports the following message formats:

* https://www.home-assistant.io/components/light.mqtt_json/[MQTT JSON Light], with support for brightness, RGB colors and white value.

Support for other message formats (e.g. https://www.home-assistant.io/components/light.mqtt/[MQTT Light])
might follow later.

--


== Documentation

* Hardware: link:hardware/led-strip-controller-esp8266/README.adoc[led-strip-controller-esp8266].


== Licenses


=== Software

The software in this repository, with the exception of included third-party works, is licensed under
the link:LICENSE_software.txt[MIT license].


=== Hardware

The hardware designs (schematics, PCB layouts, symbols and footprints etc.) in this repository,
with the exception of included third-party works, are licensed under the
link:http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].


=== Third-Party Works

Included third-party works (in the directory `3rd-party`) are licensed under their own terms.
Please check the respective licenses.